
#mqtt:
#  url: tcp://192.168.0.46:1883
#  username: lxy
#  password: 123456
#  clientId: ${random.value} # ???????? client ID ??
#  default-topic: test/# # ????

mqtt:
  username: lxy                        # ??
  password: 123456                      # ??
  host-url: tcp://192.168.0.46:1883        # mqtt??tcp??
  in-client-id: 1 #${random.value}         # ???????? client ID ??
  out-client-id: 2 #${random.value}        # ???????? client ID ??
  default-topic: tttt         # ????
  timeout: 60                                # ????
  keepalive: 60                              # ????
  clearSession: true                         # ????(???false,??????????????? ??????????????????)

