spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xtoon-boot?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ${spring.application.name}  # 连接池名字
      minimum-idle: 2 # 最小空闲连接数量
      idle-timeout: 600000 # 空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 20 # 连接池最大连接数，默认是20
      auto-commit: true # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
#mqtt:
#  url: tcp://192.168.0.46:1883
#  username: lxy
#  password: 123456
#  clientId: ${random.value} # ???????? client ID ??
#  default-topic: test/# # ????
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    #password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mqtt:
  username: lxy                        # ??
  password: 123456                      # ??
  host-url: tcp://192.168.0.46:1883        # mqtt??tcp??
  in-client-id: 1 #${random.value}         # ???????? client ID ??
  out-client-id: 2 #${random.value}        # ???????? client ID ??
  default-topic: tttt         # ????
  timeout: 60                                # ????
  keepalive: 60                              # ????
  clearSession: true                         # ????(???false,??????????????? ??????????????????)

easy-trans:
  #启用redis缓存 如果不用redis请设置为false
  is-enable-redis: true
  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置
  is-enable-global: true
  #启用平铺模式
  is-enable-tile: true
  #字典缓存放到redis 微服务模式请开启
  dict-use-redis: true
  # ruoyi相关的请开启
  is-enable-map-result: true
  autotrans:
    package: com.example.springmqttdemo.handle.**

open:
  ai:
    url: https://api.openai.com/
    token: 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


baidu:
  ocr:
    appId: 36328934
    apiKey: ws45w7B6cCH0AXESD9zKldsE
    secretKey: vzGydj1ljMax3msMlp9wfD3HEYKElF7F



